apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workflows.yadage.github.io
spec:
  group: yadage.github.io
  version: v1
  names:
    kind: Workflow
    plural: workflows
    singular: workflow
    shortNames:
    - wf
  scope: Namespaced
