apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: wflow-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: yadage.github.io/v1
    resource: workflows
  childResources:
  - apiVersion: batch/v1
    resource: jobs
    updateStrategy:
      method: Recreate
  - apiVersion: v1
    resource: configmaps
    updateStrategy:
      method: Recreate
  hooks:
    sync:
      webhook:
        url: http://wflow-controller.yadage.svc.cluster.local/sync
