apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wflow-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wflow-controller
  template:
    metadata:
      labels:
        app: wflow-controller
    spec:
      containers:
      - name: controller
        image: lukasheinrich/yadagecrdctrl
        imagePullPolicy: IfNotPresent
        env:
        - name: YADKUBE_IMAGE
          value: lukasheinrich/yadkube:citest
---
apiVersion: v1
kind: Service
metadata:
  name: wflow-controller
spec:
  selector:
    app: wflow-controller
  ports:
  - port: 80
