sudo: required
services:
- docker
language: python
python:
- '3.6'
install:
- pip install recast-atlas pyyaml
- pip install -U yadage kubernetes recast-atlas pyyaml
- cd plugins/yadage-extresult; pip install -e .;cd -
- cd plugins/yadage-kube; pip install -e .;cd -
- cd plugins/yadage-objstore; pip install -e .;cd -


- sudo apt-get install golang-1.10-go
- /usr/lib/go-1.10/bin/go version
- export GOROOT=/usr/lib/go-1.10
- /usr/lib/go-1.10/bin/go get sigs.k8s.io/kind
- curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
- echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
- sudo apt-get update
- sudo apt-get install -y kubectl
- docker build -t lukasheinrich/yadkube:citest -f images/yadkube/Dockerfile .
- kind create cluster
- export KUBECONFIG="$(kind get kubeconfig-path)"
- kubectl cluster-info

- kind load docker-image lukasheinrich/yadkube:citest
- export KUBECONFIG="$(kind get kubeconfig-path)"
- export RECAST_AUTH_USERNAME=lheinric
- export RECAST_AUTH_PASSWORD=thisisnotmypw
- eval $(recast auth write --basedir yadageauth)
- cat runner.yml |sed 's|lukasheinrich/yadkube|lukasheinrich/yadkube:citest|' > cirunner.yml
script:
- kubectl create secret generic hepauth --from-file=yadageauth/getkrb.sh
- kubectl get -o yaml secret hepauth
- kubectl create -f crd/pv.yml -f crd/pvc.yml -f crd/role.yml -f storage.yml
- kubectl create -f cirunner.yml
- sleep 60
- kubectl get pods
- kubectl get pods|grep workflow|awk '{print $1}'|xargs kubectl logs -f
- kubectl cp storage:/data/inclworkdir workdir
- cat workdir/delphes/output.lhco
