apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-config
data:
  workflow.yml: |
    dataarg: inclworkdir
    backend: kubedirectjob
    backendopts:
      kubeconfig: incluster
      path_base: /data/
      claim_name: mylocal-pvc
      purepubopts:
        exec: {logging: false}
    plugins:
    - yadageextresult.pktbackend
    ctrlopts:
      disable_prepub: true
    initdata:
      nevents: 100
    workflow: madgraph_delphes.yml
    toplevel: from-github/phenochain
    visualize: true
    cache: checksums
---
apiVersion: batch/v1
kind: Job
metadata:
  name: workflow
spec:
  template:
    spec:
      containers:
      - name: runner
        image: lukasheinrich/yadkube
        command: [yadage-run,-f,/etc/config/workflow.yml]
        workingDir: /data
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config-volume
          mountPath: /etc/config
      restartPolicy: Never
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mylocal-pvc
      - name: config-volume
        configMap:
          name: workflow-config
  backoffLimit: 0
