apiVersion: v1
kind: ConfigMap
metadata:
  name: workflowauth-config
data:
  workflow.yml: |
    dataarg: inclworkdir_auth
    backend: kubedirectjob
    backendopts:
      kubeconfig: incluster
      path_base: /data/
      claim_name: mylocal-pvc
      purepubopts:
        exec: {logging: false}
    plugins:
    - yadagekube.backends
    ctrlopts:
      disable_prepub: true
    initdata: {}
    workflow: workflow.yml
    toplevel: from-github/testing/atlas_auth
    visualize: true
---
apiVersion: batch/v1
kind: Job
metadata:
  name: workflowauth
spec:
  template:
    spec:
      containers:
      - name: runner
        image: lukasheinrich/yadkube
        command: [yadage-run,-f,/etc/config/workflow.yml]
        workingDir: /data
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config-volume
          mountPath: /etc/config
      restartPolicy: Never
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mylocal-pvc
      - name: config-volume
        configMap:
          name: workflowauth-config
  backoffLimit: 0
