apiVersion: yadage.github.io/v1
kind: Workflow
metadata:
  name: myflow
spec:
  initdata:
    nevents: 100
  toplevel: from-github/phenochain
  workflow: madgraph_delphes.yml
  backendopts:
    path_base: /data/
    purepubopts:
      exec:
        logging: false
    kubeconfig: incluster
    claim_name: mylocal-pvc
  dataarg: cifwflow-1234
  backend: kubedirectjob
  plugins:
  - yadagekube.backends
