apiVersion: yadage.github.io/v1
kind: Workflow
metadata:
  name: myflow
spec:
  initdata:
    nevents: 100
  toplevel: from-github/phenochain
  workflow: madgraph_delphes.yml
  backendopts:
    path_base: /data/
    kubeconfig: incluster
    claim_name: mylocal-pvc
  dataarg: cifwflow-123456
  backend: kubedirectjob
  plugins:
  - yadagekube.backends
