apiVersion: yadage.github.io/v1
kind: Workflow
metadata:
  name: myflow
spec:
  initdata:
    par: Josi
  toplevel: from-github/testing/busybox-helloworld
  backendopts:
    path_base: /data/
    kubeconfig: incluster
    claim_name: mylocal-pvc
  dataarg: cifwflow-7889
  backend: kubedirectjob
  visualize: true
  plugins:
  - yadagekube.backends
  workflow: workflow.yml
